name: Python Checks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Fail for all draft PRs
        if: github.event.pull_request.draft
        run: |
          exit 1
      - name: Check out environment
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.6
      - name: Checking cache
        uses: actions/cache@v2
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('stretch/cpp/*') }}
      - name: Install
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          conda install -c conda-forge \
            ffmpeg \
            cmake \
            cmake-format \
            clang-format
          make install
      - name: Lint
        run: |
          make lint
      - name: Testing
        run: |
          make test
